import { chromium } from "playwright";
import fs from "fs";
const OUT = "/private/tmp/claude-501/-Users-davidcoast-Downloads/ebf404b8-f970-4d9a-8dd3-1810f5c3ae29/scratchpad";
const run = async () => {
  const browser = await chromium.launch({ args: ["--use-angle=swiftshader"] });
  const m = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
  await m.goto("https://coastglobal.org/", { waitUntil: "networkidle", timeout: 60000 });
  await m.waitForTimeout(4500);
  fs.writeFileSync(`${OUT}/fixed-mobile-hero.png`, await m.screenshot());
  await m.close();
  const d = await browser.newPage({ viewport: { width: 1200, height: 750 } });
  await d.goto("https://coastglobal.org/", { waitUntil: "networkidle", timeout: 60000 });
  await d.mouse.move(600, 380);
  await d.waitForTimeout(4000);
  const cdp = await d.context().newCDPSession(d);
  let y = 0;
  const to = async (t: number) => { let g = 0; while (y < t - 50 && g < 400) { await d.mouse.wheel(0, Math.min(450, t - y)); await d.waitForTimeout(70); y = await d.evaluate(() => window.scrollY); g++; } };
  await to(Math.round(750 * 1.9));
  await d.waitForTimeout(1500);
  let s = await cdp.send("Page.captureScreenshot", { format: "png" });
  fs.writeFileSync(`${OUT}/fixed-d-19.png`, Buffer.from(s.data, "base64"));
  await to(Math.round(750 * 2.25));
  await d.waitForTimeout(1500);
  s = await cdp.send("Page.captureScreenshot", { format: "png" });
  fs.writeFileSync(`${OUT}/fixed-d-22.png`, Buffer.from(s.data, "base64"));
  await browser.close();
  console.log("done");
};
run();
