/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    clients: Client;
    projects: Project;
    'project-files': ProjectFile;
    'project-updates': ProjectUpdate;
    requests: Request;
    'intake-submissions': IntakeSubmission;
    'event-intake-submissions': EventIntakeSubmission;
    'contact-submissions': ContactSubmission;
    'tool-submissions': ToolSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-files': ProjectFilesSelect<false> | ProjectFilesSelect<true>;
    'project-updates': ProjectUpdatesSelect<false> | ProjectUpdatesSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    'intake-submissions': IntakeSubmissionsSelect<false> | IntakeSubmissionsSelect<true>;
    'event-intake-submissions': EventIntakeSubmissionsSelect<false> | EventIntakeSubmissionsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'tool-submissions': ToolSubmissionsSelect<false> | ToolSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'privacy-policy': PrivacyPolicy;
    'terms-of-service': TermsOfService;
    faq: Faq;
    'trusted-by': TrustedBy;
  };
  globalsSelect: {
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'terms-of-service': TermsOfServiceSelect<false> | TermsOfServiceSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'trusted-by': TrustedBySelect<false> | TrustedBySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name shown as blog post author byline.
   */
  fullName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Cloudinary Media Information
   */
  cloudinary?: {
    /**
     * Cloudinary Public ID (used for transformations)
     */
    public_id?: string | null;
    /**
     * Type of the resource (image, video, raw)
     */
    resource_type?: string | null;
    /**
     * File format
     */
    format?: string | null;
    /**
     * Secure delivery URL
     */
    secure_url?: string | null;
    /**
     * File size in bytes
     */
    bytes?: number | null;
    /**
     * Creation timestamp
     */
    created_at?: string | null;
    /**
     * Current version number
     */
    version?: string | null;
    /**
     * Unique version identifier
     */
    version_id?: string | null;
    /**
     * Width in pixels
     */
    width?: number | null;
    /**
     * Height in pixels
     */
    height?: number | null;
    /**
     * Duration in seconds (for videos)
     */
    duration?: number | null;
    /**
     * Number of pages (for PDFs)
     */
    pages?: number | null;
    /**
     * Which page of the PDF to use for thumbnails (changes will apply after saving)
     */
    selected_page?: number | null;
    /**
     * URL for the thumbnail image (automatically generated for PDFs)
     */
    thumbnail_url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Edit to customize.
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  /**
   * Auto-set when published. Override to schedule.
   */
  publishedAt?: string | null;
  category:
    | 'brand-strategy'
    | 'visual-identity'
    | 'logo-design'
    | 'web-design'
    | 'social-media'
    | 'creative-direction'
    | 'case-study'
    | 'industry-insights';
  /**
   * Auto-calculated from content.
   */
  readingTime?: number | null;
  /**
   * Brief summary shown on blog cards and SEO meta.
   */
  excerpt?: string | null;
  coverImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Select the author of this post. Leave blank to show "The Coast" as byline.
   */
  author?: (number | null) | User;
  /**
   * Add relevant tags for filtering.
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Better Auth user ID linking this client to their auth account
   */
  betterAuthUserId: string;
  email: string;
  contactName: string;
  businessName: string;
  logoUrl?: string | null;
  phone?: string | null;
  status?: ('active' | 'invited' | 'inactive') | null;
  subscriptionTier?: ('starter' | 'pro' | 'ultimate' | 'custom') | null;
  website?: string | null;
  industry?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  client: number | Client;
  title: string;
  description?: string | null;
  serviceType: 'logo' | 'flyer' | 'epk' | 'social' | 'rebrand' | 'website';
  status?: ('pending' | 'in_progress' | 'review' | 'revision' | 'completed' | 'cancelled') | null;
  priority?: ('normal' | 'high' | 'urgent') | null;
  dueDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-files".
 */
export interface ProjectFile {
  id: number;
  project: number | Project;
  fileName: string;
  fileType?: string | null;
  fileSize?: number | null;
  fileUrl?: string | null;
  file?: (number | null) | Media;
  status?: ('pending_review' | 'approved' | 'revision_requested') | null;
  clientFeedback?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-updates".
 */
export interface ProjectUpdate {
  id: number;
  project: number | Project;
  message: string;
  isInternal?: boolean | null;
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: number;
  client: number | Client;
  title: string;
  description: string;
  serviceType?: ('logo' | 'flyer' | 'epk' | 'social' | 'website' | 'rebrand' | 'other') | null;
  priority?: ('normal' | 'high' | 'urgent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-submissions".
 */
export interface IntakeSubmission {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  businessName: string;
  website?: string | null;
  businessDescription: string;
  idealCustomer?: string | null;
  servicesInterested?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  brandVibes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  colorPreferences?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  colorsToAvoid?: string | null;
  brandsAdmired?: string | null;
  budget?: string | null;
  timeline?: string | null;
  additionalVision?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-intake-submissions".
 */
export interface EventIntakeSubmission {
  id: number;
  contactName: string;
  email: string;
  phone?: string | null;
  eventName: string;
  eventType?: string | null;
  eventDate?: string | null;
  eventLocation?: string | null;
  expectedAttendees?: string | null;
  servicesNeeded?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  budget?: string | null;
  timeline?: string | null;
  eventDescription: string;
  additionalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-submissions".
 */
export interface ToolSubmission {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  role?: string | null;
  tool: 'brand-quiz' | 'brand-checklist' | '3-second-test';
  score?: number | null;
  /**
   * Quiz tier, checklist band, or test outcome
   */
  resultTier?: string | null;
  /**
   * Tool-specific response data
   */
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-files';
        value: number | ProjectFile;
      } | null)
    | ({
        relationTo: 'project-updates';
        value: number | ProjectUpdate;
      } | null)
    | ({
        relationTo: 'requests';
        value: number | Request;
      } | null)
    | ({
        relationTo: 'intake-submissions';
        value: number | IntakeSubmission;
      } | null)
    | ({
        relationTo: 'event-intake-submissions';
        value: number | EventIntakeSubmission;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'tool-submissions';
        value: number | ToolSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinary?:
    | T
    | {
        public_id?: T;
        resource_type?: T;
        format?: T;
        secure_url?: T;
        bytes?: T;
        created_at?: T;
        version?: T;
        version_id?: T;
        width?: T;
        height?: T;
        duration?: T;
        pages?: T;
        selected_page?: T;
        thumbnail_url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  category?: T;
  readingTime?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  betterAuthUserId?: T;
  email?: T;
  contactName?: T;
  businessName?: T;
  logoUrl?: T;
  phone?: T;
  status?: T;
  subscriptionTier?: T;
  website?: T;
  industry?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  client?: T;
  title?: T;
  description?: T;
  serviceType?: T;
  status?: T;
  priority?: T;
  dueDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-files_select".
 */
export interface ProjectFilesSelect<T extends boolean = true> {
  project?: T;
  fileName?: T;
  fileType?: T;
  fileSize?: T;
  fileUrl?: T;
  file?: T;
  status?: T;
  clientFeedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-updates_select".
 */
export interface ProjectUpdatesSelect<T extends boolean = true> {
  project?: T;
  message?: T;
  isInternal?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  client?: T;
  title?: T;
  description?: T;
  serviceType?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-submissions_select".
 */
export interface IntakeSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  businessName?: T;
  website?: T;
  businessDescription?: T;
  idealCustomer?: T;
  servicesInterested?: T;
  brandVibes?: T;
  colorPreferences?: T;
  colorsToAvoid?: T;
  brandsAdmired?: T;
  budget?: T;
  timeline?: T;
  additionalVision?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-intake-submissions_select".
 */
export interface EventIntakeSubmissionsSelect<T extends boolean = true> {
  contactName?: T;
  email?: T;
  phone?: T;
  eventName?: T;
  eventType?: T;
  eventDate?: T;
  eventLocation?: T;
  expectedAttendees?: T;
  servicesNeeded?: T;
  budget?: T;
  timeline?: T;
  eventDescription?: T;
  additionalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-submissions_select".
 */
export interface ToolSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  role?: T;
  tool?: T;
  score?: T;
  resultTier?: T;
  answers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content for the /privacy page. Edit here to update the live Privacy Policy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  /**
   * Date displayed at the top of the Privacy Policy page.
   */
  lastUpdated?: string | null;
  /**
   * Full Privacy Policy text. Use headings, paragraphs, and lists.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the /terms page. Edit here to update the live Terms of Service.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-service".
 */
export interface TermsOfService {
  id: number;
  /**
   * Date displayed at the top of the Terms of Service page.
   */
  lastUpdated?: string | null;
  /**
   * Full Terms of Service text. Use headings, paragraphs, and lists.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage frequently asked questions displayed on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * Add, reorder, or remove FAQ entries. Drag to reorder.
   */
  items?:
    | {
        question: string;
        answer: string;
        category?: ('general' | 'pricing' | 'process' | 'support') | null;
        published?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the brands shown in the "Trusted By" sections (hero marquee and dedicated section). Each entry can be a text name, a logo image, or both.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted-by".
 */
export interface TrustedBy {
  id: number;
  /**
   * Add, reorder, or remove brands. Provide a name, a logo, or both. Logos are rendered at a consistent size.
   */
  items?:
    | {
        /**
         * Brand name. Shown as a fallback if no logo is provided.
         */
        name: string;
        /**
         * Optional logo image. Prefer transparent PNG or SVG. Will be rendered at a consistent height.
         */
        logo?: (number | null) | Media;
        /**
         * Optional link to the brand website.
         */
        url?: string | null;
        published?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  lastUpdated?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-service_select".
 */
export interface TermsOfServiceSelect<T extends boolean = true> {
  lastUpdated?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        category?: T;
        published?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted-by_select".
 */
export interface TrustedBySelect<T extends boolean = true> {
  items?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        published?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}